### ISSUE TITLE
Go style-guide

### ISSUE THREAD

**Issue by tudormunteanu** [oanaOM/auction-house#2]
Have the Go coding style-guides and best practices been followed?

Naming function, naming vars, module naming, comments style and spacing, etc

**Comment by tudormunteanu** [comment]
I read a bit on https://github.com/smallnest/go-best-practices

**Comment by oanaOM** [comment]
Only some of them. Thank you very much for the resources. I made some improvements to the coding style to accommodate Go's style :) Could you please have a look and let me know your thoughts?

**Comment by tudormunteanu** [comment]
Much easier to read. Looks good.
