### ISSUE TITLE
Expected vs received output

### ISSUE THREAD

**Issue by tudormunteanu** [oanaOM/auction-house#3]
Received:
|20|toaster_1|8|SOLD|12.5|0|0|0|
|20|tv_1|0|UNSOLD|0|0|0|0|

Expected:
20|toaster_1|8|SOLD|12.50|3|20.00|7.50
20|tv_1||UNSOLD|0|2|200.00|150.00

Missing:
- price_paid
- total_bid_count
- highest_bid
- lowest_bid

**Comment by oanaOM** [comment]
@tudormunteanu Fixed. You should be able to see now in the output the missing values.

**Comment by tudormunteanu** [comment]
Almost there. 

Received:
```
|20|toaster_1|8|SOLD|12.5|3|20|7.5|
|20|tv_1|0|UNSOLD|0|2|200|150|
```
vs expected:
```
20|toaster_1|8|SOLD|12.50|3|20.00|7.50
20|tv_1||UNSOLD|0|2|200.00|150.00
```

Notice:
1. Separators. The | (pipe) acts like a divider in a format similar to CSV. Why did you choose to start your row with it?
2. The number of digits after 0 is not as expected. 20 vs 20.00 albeit equal, is less transparent and might hide some rounding.

**Comment by oanaOM** [comment]
@tudormunteanu 
1. It wasn't intentionally . I've correct it now.
2. Makes perfect sense. The values are now showing 2 digits.
